CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Conveniences" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT "PK_Conveniences" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Password" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Advertisements" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdAuthor" bigint NOT NULL,
    CONSTRAINT "PK_Advertisements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Advertisements_Users_IdAuthor" FOREIGN KEY ("IdAuthor") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ConversationRooms" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "DateCreate" timestamp with time zone NOT NULL,
    "DeletionStatus" boolean NOT NULL,
    "IdOneUser" bigint NOT NULL,
    "IdTwoUser" bigint NOT NULL,
    CONSTRAINT "PK_ConversationRooms" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ConversationRooms_Users_IdOneUser" FOREIGN KEY ("IdOneUser") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ConversationRooms_Users_IdTwoUser" FOREIGN KEY ("IdTwoUser") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AdvertisementConveniences" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdAdvertisement" bigint NOT NULL,
    "IdConvenience" bigint NOT NULL,
    CONSTRAINT "PK_AdvertisementConveniences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AdvertisementConveniences_Advertisements_IdAdvertisement" FOREIGN KEY ("IdAdvertisement") REFERENCES "Advertisements" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AdvertisementConveniences_Conveniences_IdConvenience" FOREIGN KEY ("IdConvenience") REFERENCES "Conveniences" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Photos" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdAdvertisement" bigint NOT NULL,
    CONSTRAINT "PK_Photos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Photos_Advertisements_IdAdvertisement" FOREIGN KEY ("IdAdvertisement") REFERENCES "Advertisements" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Rental_requests" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdAuthorRentalRequest" bigint NOT NULL,
    "IdNeedAdvertisement" bigint NOT NULL,
    CONSTRAINT "PK_Rental_requests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Rental_requests_Advertisements_IdNeedAdvertisement" FOREIGN KEY ("IdNeedAdvertisement") REFERENCES "Advertisements" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Rental_requests_Users_IdAuthorRentalRequest" FOREIGN KEY ("IdAuthorRentalRequest") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Messages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdConversationRoom" bigint NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Messages_ConversationRooms_IdConversationRoom" FOREIGN KEY ("IdConversationRoom") REFERENCES "ConversationRooms" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Reviews" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdNeedRentalRequest" bigint NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reviews_Rental_requests_IdNeedRentalRequest" FOREIGN KEY ("IdNeedRentalRequest") REFERENCES "Rental_requests" ("Id") ON DELETE CASCADE
);

INSERT INTO "Users" ("Id", "Email", "Password")
VALUES (1, 'admin@example.com', '123456');

CREATE INDEX "IX_AdvertisementConveniences_IdAdvertisement" ON "AdvertisementConveniences" ("IdAdvertisement");

CREATE INDEX "IX_AdvertisementConveniences_IdConvenience" ON "AdvertisementConveniences" ("IdConvenience");

CREATE INDEX "IX_Advertisements_IdAuthor" ON "Advertisements" ("IdAuthor");

CREATE INDEX "IX_ConversationRooms_IdOneUser" ON "ConversationRooms" ("IdOneUser");

CREATE INDEX "IX_ConversationRooms_IdTwoUser" ON "ConversationRooms" ("IdTwoUser");

CREATE INDEX "IX_Messages_IdConversationRoom" ON "Messages" ("IdConversationRoom");

CREATE INDEX "IX_Photos_IdAdvertisement" ON "Photos" ("IdAdvertisement");

CREATE INDEX "IX_Rental_requests_IdAuthorRentalRequest" ON "Rental_requests" ("IdAuthorRentalRequest");

CREATE INDEX "IX_Rental_requests_IdNeedAdvertisement" ON "Rental_requests" ("IdNeedAdvertisement");

CREATE INDEX "IX_Reviews_IdNeedRentalRequest" ON "Reviews" ("IdNeedRentalRequest");

SELECT setval(
    pg_get_serial_sequence('"Users"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Users") + 1,
        nextval(pg_get_serial_sequence('"Users"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241001091333_Initil', '8.0.8');

COMMIT;

